import sys
import argparse
import time
import requests
from bs4 import BeautifulSoup
from datetime import datetime, timedelta

# Import your existing local config file
import config

# --- CONFIGURATION ---
EMAIL = config.HDID_EMAIL
PASSWORD = config.HDID_PASSWORD
COURSE_ID = config.HDID_COURSE_ID
DAYS_IN_ADVANCE = 7 # Set to your club's exact booking window (e.g., 7, 14)

# --- SETUP SESSION ---
def hdid_login():
    """Handles the ASP.NET hidden token login flow."""
    session = requests.Session()
    session.headers.update({
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    })

    LOGIN_URL = "https://passport.howdidido.com/Account/Login"
    
    print("[*] Fetching login page for anti-forgery token...")
    r = session.get(LOGIN_URL, timeout=15)
    r.raise_for_status()

    soup = BeautifulSoup(r.text, "html.parser")
    hidden_fields = {
        inp.get("name"): inp.get("value", "")
        for inp in soup.find_all("input", {"type": "hidden"})
        if inp.get("name")
    }

    post_data = {
        **hidden_fields,
        "EmailAddress": EMAIL,
        "Password": PASSWORD,
        "RememberMe": "true"
    }

    print("[*] Submitting login credentials...")
    r2 = session.post(LOGIN_URL, data=post_data, allow_redirects=True, timeout=15)
    r2.raise_for_status()

    if "Sign Out" in r2.text or "HowDidiDo" in r2.text:
        print(" -> Login Successful!\n")
        return session
    else:
        raise Exception("Login Failed. Check credentials in config.py.")

# --- BOOKING LOGIC ---
def book_tee_time(session, target_date, target_time):
    """
    Attempts to lock and confirm a tee time. Returns True if successful.
    target_date: YYYY-MM-DD
    target_time: HH:MM
    """
    datetime_str = f"{target_date}T{target_time}"
    
    # 1. THE LOCK PHASE
    LOCK_URL = (
        f"https://howdidido-whs.clubv1.com/HDIDBooking/BookingAdd"
        f"?dateTime={datetime_str}&courseId={COURSE_ID}&startPoint=1"
        f"&crossOverStartPoint=0&crossOverMinutes=0&releasedReservation=False"
    )

    print(f"[{datetime.now().strftime('%H:%M:%S')}] Attempting to LOCK {target_date} at {target_time}...")
    r_lock = session.get(LOCK_URL, timeout=10)
    
    if "already been booked" in r_lock.text.lower() or "unavailable" in r_lock.text.lower():
        print(" -> FAILED: Time is locked or unavailable.")
        return False

    # 2. THE SCRAPE PHASE
    soup = BeautifulSoup(r_lock.text, "html.parser")
    form = soup.find("form")
    
    if not form:
        print(" -> FAILED: Could not find confirmation form. Timesheet might not be open yet.")
        return False

    # Extract all the default hidden inputs generated by the lock
    payload = {
        inp.get("name"): inp.get("value", "")
        for inp in form.find_all("input")
        if inp.get("name")
    }
    
    booking_lock_id = payload.get('BookingLockId')
    print(f" -> Time LOCKED. BookingLockId: {booking_lock_id}")

    # =====================================================================
    # 3. ADD BUDDIES PHASE
    # Injecting Phil and Jason directly into the final Confirm payload
    # =====================================================================
    print(" -> Injecting Phil Bentham and Jason Corkill into the booking...")
    
    # Player 2: Phil Bentham
    payload["Players[0].PersonID"] = "2512799"
    payload["Players[0].Forename"] = "Phil"
    payload["Players[0].Surname"] = "Bentham"
    payload["Players[0].TeeSheetPosition"] = "2"
    payload["Players[0].Amount"] = "0"
    payload["Players[0].GreenFeeRateID"] = "0"

    # Player 3: Jason Corkill
    payload["Players[1].PersonID"] = "1446025"
    payload["Players[1].Forename"] = "Jason"
    payload["Players[1].Surname"] = "Corkill"
    payload["Players[1].TeeSheetPosition"] = "3"
    payload["Players[1].Amount"] = "0"
    payload["Players[1].GreenFeeRateID"] = "0"
    # =====================================================================

    time.sleep(1.5) # Brief pause to mimic human speed to avoid WAF bans

    # 4. THE CONFIRM PHASE
    action_path = form.get("action", "HDIDBooking/bookingConfirmAndPay")
    if action_path.startswith("/"):
        action_path = action_path[1:]
        
    CONFIRM_URL = f"https://howdidido-whs.clubv1.com/{action_path}"

    print(f"[{datetime.now().strftime('%H:%M:%S')}] Confirming booking...")
    r_confirm = session.post(CONFIRM_URL, data=payload, timeout=10)

    if "Booking Confirmed" in r_confirm.text or "Thank You" in r_confirm.text:
        print(" -> SUCCESS! Tee time officially booked for Phil D, Phil B, and Jason C.")
        return True
    else:
        print(" -> FAILED during final confirmation step.")
        return False

# --- MAIN EXECUTION ---
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="HDID Auto Booker")
    parser.add_argument("--tuesday", action="store_true", help="Book the 08:32 Tuesday slot")
    parser.add_argument("--friday", action="store_true", help="Book the 08:00 Friday slot")
    args = parser.parse_args()

    if not args.tuesday and not args.friday:
        print("Error: You must specify either --tuesday or --friday")
        sys.exit(1)

    # Calculate target date based on how many days in advance booking opens
    target_date_obj = datetime.today() + timedelta(days=DAYS_IN_ADVANCE)
    target_date = target_date_obj.strftime("%Y-%m-%d")

    if args.tuesday:
        target_time = "08:32"
        expected_weekday = 1 # 0=Mon, 1=Tue, 2=Wed...
    elif args.friday:
        target_time = "08:00"
        expected_weekday = 4 # 4=Fri

    if target_date_obj.weekday() != expected_weekday:
        print(f"CRITICAL: Calculated target date ({target_date}) is not the correct day of the week.")
        print("Check your DAYS_IN_ADVANCE variable. Script will now exit.")
        sys.exit(1)

    print(f"=== 828ers Auto-Booker Initiated ===")
    print(f"Target: {target_date} @ {target_time} (Booking window: +{DAYS_IN_ADVANCE} days)\n")

    try:
        my_session = hdid_login()
    except Exception as e:
        print(f"CRITICAL: {e}")
        sys.exit(1)

    # Polling loop: Try for up to 5 minutes (30 attempts * 10 seconds)
    MAX_ATTEMPTS = 30
    for attempt in range(1, MAX_ATTEMPTS + 1):
        print(f"--- Attempt {attempt} of {MAX_ATTEMPTS} ---")
        
        try:
            success = book_tee_time(my_session, target_date, target_time)
            if success:
                print("\nBooking loop finished successfully. Exiting.")
                sys.exit(0)
        except Exception as e:
            print(f" -> Encountered error during attempt: {e}")
        
        # Wait 10 seconds before hitting the API again
        if attempt < MAX_ATTEMPTS:
            print(" -> Retrying in 10 seconds...\n")
            time.sleep(10)

    print("\n[!] Exhausted all retry attempts. Booking failed.")